#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080
sed -i "s/#user www-data;/user nginx;/g" /etc/nginx/nginx.conf
sed -i "s/listen 80 default_server;/listen 8080 default_server;/g" /etc/nginx/sites-available/default
sed -i "s/listen \[::\]:80 default_server;/listen [::]:8080 default_server;/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
service nginx restart
