#!/usr/bin/env bash
# Start Apache to return a
# page returning Hello Holberton
sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/wwww/html/index.html
sudo /etc/init.d/apache2 restart
