#!/usr/bin/env bash
# install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "<html><body>Holberton School</body></html>" > /var/www/html/index.nginx-debian.html 
sudo killall nginx
sudo nginx
