#!/usr/bin/env bash

# Install nginx
apt-get update
apt-get install -y nginx

# Create a new configuration file for nginx
echo "server {
    listen 80;
    location / {
        return 200 'Holberton School for the win!';
    }
}" > /etc/nginx/sites-available/default

# Restart nginx without using systemctl
killall nginx
nginx
